name: Lint, build, and scan

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  lint-build:
    name: Lint and build

    runs-on: ubuntu-latest

    steps:
      - name: Preserve line endings
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Check types
        run: npm run typecheck
        env:
          CI: true

      - name: Check formatting
        run: npm run prettier
        env:
          CI: true

      - name: Lint
        run: npm run lint
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true

  fossa-scan:
    name: FOSSA scan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: FOSSA scan
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
